### ISSUE TITLE
As a registered user, I want to create a new roasting session for which I will upload a picture and be the host, so that I can get roasted

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#10]
### Acceptance Criteria

- [ ] From a button on the starting screen after login, a user can create a new roasting session.
- [ ] The user becomes the host and has to upload a picture to start the session.
- [ ] The user can select and upload a picture from his device.
- [ ] Pictures may not be larger than 3MB. If a user tries uploading a picture that is too large, an error message is shown.
- [ ] The host can add a title to their picture.
- [ ] The host can set session settings, e.g. maximum number of participants.
- [ ] Only registered users can create roasting sessions.

### Development Tasks

- [x] sopra-fs22-group-18/server#141
- [x] sopra-fs22-group-18/server#145
- [x] sopra-fs22-group-18/server#130
- [x] sopra-fs22-group-18/client#24
- [x] sopra-fs22-group-18/client#25
- [ ] sopra-fs22-group-18/server#166
- [x] sopra-fs22-group-18/client#57
- [x] sopra-fs22-group-18/client#56
- [ ] sopra-fs22-group-18/client#66
