### ISSUE TITLE
As a registered user, I want to join an active roasting session and become a participant, so that I can view a picture and compete for the best comment/roast.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#11]
### Acceptance Criteria

- [x] On the starting screen after login, the user can see how many active roasting sessions there are.
- [x] The user can click a button to “Join a session” and will be added to the next session determined in the queue. From the user’s viewpoint this will be a random assignment.
- [x] Users can only be added to sessions that are active and that have not yet reached the maximum number of participants. 
- [x] The user will be redirected to the roasting session and see the picture and any previous comments.
- [x] Only registered users can join roasting sessions.

### Development Tasks

- [x] sopra-fs22-group-18/server#150
- [x] sopra-fs22-group-18/client#51
- [x] sopra-fs22-group-18/client#52
- [x] sopra-fs22-group-18/server#164
- [x] sopra-fs22-group-18/client#53
- [x] sopra-fs22-group-18/server#165
- [x] sopra-fs22-group-18/client#59
- [x] sopra-fs22-group-18/server#176
- [x] sopra-fs22-group-18/server#177
- [x] sopra-fs22-group-18/server#179
- [x] sopra-fs22-group-18/server#182
