### ISSUE TITLE
As a participant, I want to comment on the picture in the roast session, so that I can make fun of it and compete for the best roast.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#12]
### Acceptance Criteria

- [x] In the session screen, the participant has a comment field where they can type their comment.
- [x] Once the participant clicks a button to submit their comment, it will be visible in the roast session for the host and all participants within a minimal time delay.
- [x] A participant may submit as many comments as they like as long as the session is active.

### Development Tasks

- [x] sopra-fs22-group-18/server#147
- [x] sopra-fs22-group-18/server#148
- [x] sopra-fs22-group-18/client#48
- [x] sopra-fs22-group-18/client#49
- [x]  sopra-fs22-group-18/client#50
- [x]  sopra-fs22-group-18/server#160
- [x]  sopra-fs22-group-18/client#40
- [x]  sopra-fs22-group-18/client#41
- [x] sopra-fs22-group-18/server#161
- [x] #172
- [x] sopra-fs22-group-18/client#76
