### ISSUE TITLE
As a host, I want to declare who the winner of the roast session is, so that I can reward the best roaster and end the session.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#13]
### Acceptance Criteria
- [ ] The host should see a button on the roast session that allows them to declare the winner and end the session. 
- [ ] When the host clicks on the button, they can select the winner from the participants. 
- [ ] A message is shown to everyone in the session that it has ended and displays the winner’s username. 
- [ ] Below the message there is an exit session button. By clicking the button, users (host and participants) are redirected to the starting page. 
- [ ] The roast session becomes inactive as soon as a winner is declared and no new participants can join. 

### Development Tasks

- [x] sopra-fs22-group-18/client#44
- [x] sopra-fs22-group-18/client#45
- [x] sopra-fs22-group-18/client#46
- [x] sopra-fs22-group-18/client#47
- [x] sopra-fs22-group-18/server#156
- [x] sopra-fs22-group-18/client#63
