### ISSUE TITLE
As a participant, I want to be able to leave a roasting session anytime, so that I don’t waste my time if it is not amusing.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#14]
### Acceptance Criteria

- [x] On the session screen, there is an exit session button.

- [x] If a participants clicks the button they are redirected to the starting page and removed from the session.

- [x] A message is shown to the host and the other participants that the user has left the session.

- [x] Hosts will not have access to this button, they can only exit the session by closing it and declaring a winner.

### Development Tasks

- [x] sopra-fs22-group-18/server#128
- [x] sopra-fs22-group-18/client#17
- [x] sopra-fs22-group-18/client#18
- [x] sopra-fs22-group-18/client#19
- [x] sopra-fs22-group-18/server#127
