### ISSUE TITLE
As a registered user, I want to choose which active roasting session to join by entering an identifier, so that I can play with my friend.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#15]
### Acceptance Criteria

- [x] When a user creates a new session, they can select an option to start a private session with id. 
- [x] An id is generated and displayed to the host so that they can share it with their friends.
- [x] On the starting screen, the user can see a “Join session with id” button.
- [x] When clicking the button the user is asked to enter the session id they want to join. 
- [x] If the user enters a valid session id, he is redirected to the session and added as a participant. 
- [x] If the user enters a session id that does not exist, he gets an error message to that effect. 
- [x] If the user enters a session id that is no longer active, he gets an error message to that effect. 
- [x] If the user enters a session id that has already reached the maximum number of participants, he gets an error message to that effect. 

### Development Task

- [x] sopra-fs22-group-18/client#64
- [x] sopra-fs22-group-18/server#192
- [x] sopra-fs22-group-18/server#191
- [x] sopra-fs22-group-18/server#190
- [x] sopra-fs22-group-18/client#86
