### ISSUE TITLE
As a user, I want to be able to report a session to an admin, so that I can draw attention to other users who are being inappropriate.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#20]
### Acceptance Criteria

- [ ] On the session screen, each participant and the host has a button to report the session. 
- [ ] On click, the user is asked to select a reason from a list (inappropriate language, racism, sexual harrassement, …) and provide a short comment on why they are reporting the session. 
- [ ] Once any user has reported a session, the session is closed for everyone and a message is displayed saying that the session has been reported for reason [reason] and administrators may take further actions. 

### Development Task

- [x] sopra-fs22-group-18/client#78
- [x] sopra-fs22-group-18/client#77
- [x] sopra-fs22-group-18/server#209
- [x] sopra-fs22-group-18/server#210
- [x] sopra-fs22-group-18/server#211
