### ISSUE TITLE
As a host I want to close the session without selecting a winner

### ISSUE THREAD

**Issue by carolernst-uzh** [sopra-fs22-group-18/server#223]
### Acceptance Criteria

- [x] The host can press a button in the session screen to close the session
- [x] Each participant receives a message from the server informing them that the session has been closed

### Development Task

- [x] sopra-fs22-group-18/server#225
- [x] sopra-fs22-group-18/server#226
- [x] sopra-fs22-group-18/client#87
