### ISSUE TITLE
As an unregistered user I want to be able to register to Roast Me, login, and logout, so that I can use the application, which is only available to registered users. 

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#3]
### Acceptance Criteria

- [x] The user can choose their own credentials (username and password), though usernames must be unique.
- [x] Upon successful registration, the posts overview screen (see below) is shown and the user is automatically logged in.
- [x] If the username is already taken, an error message is displayed asking the user to select a different username.
- [x] Users can log in and log out of their registered profile.
- [x] If the user tries to login with a username that does not exist or enters the wrong password, an error message to that effect is displayed.

### Development Tasks

- [x] sopra-fs22-group-18/client#10
- [x] sopra-fs22-group-18/client#11
- [x] sopra-fs22-group-18/server#116
- [x] sopra-fs22-group-18/server#118
- [x] sopra-fs22-group-18/server#119
- [x] sopra-fs22-group-18/server#120
- [x] sopra-fs22-group-18/server#121
- [x] sopra-fs22-group-18/server#174
- [x] sopra-fs22-group-18/server#175
- [x] sopra-fs22-group-18/server#178 
- [x] sopra-fs22-group-18/server#180
- [x] sopra-fs22-group-18/server#195
- [x] sopra-fs22-group-18/server#197
- [ ] sopra-fs22-group-18/client#67
- [x] sopra-fs22-group-18/client#68
